"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

type Overview = { users: number; activeUsers: number; suspendedUsers: number; communities: number; pendingVerifications: number; inventoryEvents: number; unreadNotifications: number };
type User = { id: string; email: string; firstName: string | null; lastName: string | null; role: string; status: "ACTIVE" | "SUSPENDED"; membership: { city: { name: string }; state: { code: string } } | null };
type Dispute = { id: string; occurredAt: string; actor: { email: string }; city: { name: string; state: { code: string } } };

export default function AdminPage() {
  const [overview, setOverview] = useState<Overview | null>(null); const [users, setUsers] = useState<User[]>([]); const [disputes, setDisputes] = useState<Dispute[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = async () => { try { const [summary, userData, disputeData] = await Promise.all([api<Overview>("/admin/overview"), api<{ users: User[] }>("/admin/users"), api<{ disputes: Dispute[] }>("/admin/disputes")]); setOverview(summary); setUsers(userData.users); setDisputes(disputeData.disputes); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load administration console"); } };
  useEffect(() => { void load(); }, []);
  async function changeStatus(user: User) { const status = user.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE"; setBusy(user.id); setError(""); try { await api(`/admin/users/${user.id}/status`, { method: "PATCH", body: JSON.stringify({ status, reason: "Manual administrator review" }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to change status"); } finally { setBusy(""); } }
  return <main className="dashboard"><header className="dashboard-nav"><Link className="brand" href="/dashboard">TITAN ADMIN</Link><Link className="text-link" href="/dashboard">Exit administration</Link></header><section className="welcome"><div><p className="eyebrow">SPRINT 043 · ADMINISTRATION ENGINE</p><h1>Operations control</h1><p>Protected oversight for platform membership, disputes, and system activity.</p></div></section>{error && <section className="admin-error"><p className="error" role="alert">{error}</p></section>}{overview && <section className="admin-stats"><article><span>Total users</span><strong>{overview.users}</strong></article><article><span>Active</span><strong>{overview.activeUsers}</strong></article><article><span>Suspended</span><strong>{overview.suspendedUsers}</strong></article><article><span>Communities</span><strong>{overview.communities}</strong></article><article><span>Inventory events</span><strong>{overview.inventoryEvents}</strong></article><article><span>Rejected claims</span><strong>{disputes.length}</strong></article></section>}<section className="admin-grid"><article className="panel admin-users"><p className="eyebrow">MEMBER OVERSIGHT</p><h2>Accounts</h2><div className="table-scroll"><table><thead><tr><th>Member</th><th>Community</th><th>Role</th><th>Status</th><th>Control</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{`${user.firstName ?? ""} ${user.lastName ?? ""}`.trim() || "TITAN Member"}</strong><small>{user.email}</small></td><td>{user.membership ? `${user.membership.city.name}, ${user.membership.state.code}` : "Not selected"}</td><td>{user.role}</td><td><span className={`status ${user.status.toLowerCase()}`}>{user.status}</span></td><td><button className="text-button admin-control" disabled={busy === user.id} onClick={() => changeStatus(user)}>{busy === user.id ? "Saving…" : user.status === "ACTIVE" ? "Suspend" : "Reactivate"}</button></td></tr>)}</tbody></table></div></article><article className="panel"><p className="eyebrow">VERIFICATION OVERSIGHT</p><h2>Rejected contributions</h2>{disputes.length ? <ul className="dispute-list">{disputes.map((item) => <li key={item.id}><div><strong>{item.actor.email}</strong><small>{item.city.name}, {item.city.state.code} · {new Date(item.occurredAt).toLocaleDateString()}</small></div><span className="status rejected">REJECTED</span></li>)}</ul> : <p className="empty">No rejected contributions require review.</p>}</article></section></main>;
}
