"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { useRealtime } from "@/lib/realtime";

type Dashboard = { user: { firstName: string; role: string }; community: { city: string; state: string; members: number; target: number; progress: number }; stateProgress: { completedCities: number; targetCities: number; progress: number }; titanScore: number; rank: number; inventory: { totalTokens: number; verifiedTokens: number; pendingTokens: number; participants: number }; nextMission: { title: string; description: string; reward: number }; activity: { id: string; text: string; occurredAt: string }[]; achievements: { id: string; name: string; earned: boolean }[] };
export default function DashboardPage() {
  const router = useRouter(); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState("");
  useEffect(() => { api<Dashboard>("/dashboard").then(setData).catch(reason => { const message = reason instanceof Error ? reason.message : "Unable to load dashboard"; setError(message); if (message.includes("community selection")) router.push("/onboarding"); }); }, [router]);
  useRealtime(() => { void api<Dashboard>("/dashboard").then(setData); });
  function logout() { api("/auth/logout", { method: "POST" }).finally(() => { localStorage.removeItem("titan_access_token"); router.push("/login"); }); }
  if (error) return <main className="centered"><section className="form-card"><h1>Dashboard unavailable</h1><p className="error">{error}</p><Link className="button" href="/login">Return to sign in</Link></section></main>;
  if (!data) return <main className="centered"><p className="loading">Loading your community…</p></main>;
  return <main className="dashboard"><header className="dashboard-nav"><Link className="brand" href="/dashboard">TITAN</Link><div><Link className="text-link" href="/inventory">My inventory</Link><span className="role-pill">{data.user.role}</span><button className="text-button" onClick={logout}>Sign out</button></div></header><section className="welcome"><div><p className="eyebrow">COMMUNITY COMMAND CENTER</p><h1>Good morning, {data.user.firstName}.</h1><p>Your contribution is helping {data.community.city} move forward.</p></div><Link className="button" href="/inventory">Add participant</Link></section><section className="stat-grid four"><article className="stat-card accent"><span>TITAN Score</span><strong>{data.titanScore}</strong><small>+50 for joining</small></article><article className="stat-card"><span>My inventory</span><strong>{data.inventory.totalTokens}</strong><small>{data.inventory.verifiedTokens} verified · {data.inventory.pendingTokens} pending</small></article><article className="stat-card"><span>Community progress</span><strong>{data.community.progress}%</strong><small>{data.community.members} of {data.community.target} verified people</small></article><article className="stat-card"><span>Community position</span><strong>#{data.rank}</strong><small>{data.community.city}, {data.community.state}</small></article></section><section className="dashboard-grid"><article className="panel progress-panel"><div className="panel-heading"><div><p className="eyebrow">CITY PROGRESS</p><h2>{data.community.city}</h2></div><strong>{data.community.progress}%</strong></div><div className="progress-track"><span style={{ width: `${data.community.progress}%` }} /></div><div className="progress-meta"><span>{data.community.members} verified</span><span>{data.community.target - data.community.members} remaining</span></div><div className="state-line"><span>{data.community.state} state progress</span><strong>{data.stateProgress.completedCities} / {data.stateProgress.targetCities} cities</strong></div></article><article className="panel mission"><p className="eyebrow">NEXT MISSION</p><h2>{data.nextMission.title}</h2><p>{data.nextMission.description}</p><div className="reward">+{data.nextMission.reward} TITAN points</div><Link className="button" href="/inventory">Start mission</Link></article><article className="panel"><p className="eyebrow">RECENT ACTIVITY</p><h2>Your participation</h2>{data.activity.length ? <ul className="activity-list">{data.activity.map(item => <li key={item.id}><span className="activity-dot" /><div><strong>{item.text}</strong><small>{new Date(item.occurredAt).toLocaleDateString()}</small></div></li>)}</ul> : <p className="empty">Your verified activity will appear here.</p>}</article><article className="panel"><p className="eyebrow">ACHIEVEMENTS</p><h2>Recognition</h2><div className="achievement"><span>✓</span><div><strong>{data.achievements[0]?.name}</strong><small>Community selected</small></div></div></article></section></main>;
}
