"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
type Point = { day: string; count: number };
type Analytics = { summary: { users: number; onboarded: number; communities: number; recordedContributions: number; verifiedContributions: number; rejectedContributions: number; onboardingRate: number; verificationRate: number; rejectionRate: number; verifiedTokens: number }; trends: { inventoryEvents: Point[]; newMemberships: Point[] }; generatedAt: string };
function Trend({ title, data, color }: { title: string; data: Point[]; color: string }) { const max = Math.max(1, ...data.map((point) => point.count)); return <article className="panel trend-panel"><p className="eyebrow">30-DAY TREND</p><h2>{title}</h2><div className="bar-chart" role="img" aria-label={`${title} over the last 30 days`}>{data.map((point) => <span key={point.day} title={`${point.day}: ${point.count}`} style={{ height: `${Math.max(3, (point.count / max) * 100)}%`, background: color }} />)}</div><div className="chart-axis"><span>{data[0]?.day.slice(5)}</span><span>{data.at(-1)?.day.slice(5)}</span></div></article>; }
export default function AnalyticsPage() {
  const [data, setData] = useState<Analytics | null>(null); const [error, setError] = useState("");
  useEffect(() => { api<Analytics>("/admin/analytics").then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load analytics")); }, []);
  const funnel = useMemo(() => data ? [{ label: "Registered", value: data.summary.users }, { label: "Onboarded", value: data.summary.onboarded }, { label: "Contributed", value: data.summary.recordedContributions }, { label: "Verified", value: data.summary.verifiedContributions }] : [], [data]);
  const maxFunnel = Math.max(1, ...funnel.map((step) => step.value));
  return <main className="dashboard"><header className="dashboard-nav"><Link className="brand" href="/dashboard">TITAN ANALYTICS</Link><div><Link className="text-link" href="/admin">Administration</Link><Link className="text-link" href="/dashboard">Exit analytics</Link></div></header><section className="welcome"><div><p className="eyebrow">SPRINT 044 · ANALYTICS ENGINE</p><h1>Participation intelligence</h1><p>Operating metrics derived from TITAN’s immutable participation records.</p></div></section>{error && <section className="admin-error"><p className="error" role="alert">{error}</p></section>}{data && <><section className="analytics-stats"><article><span>Members</span><strong>{data.summary.users}</strong><small>{data.summary.onboardingRate}% onboarded</small></article><article><span>Communities</span><strong>{data.summary.communities}</strong><small>Active city records</small></article><article><span>Contributions</span><strong>{data.summary.recordedContributions}</strong><small>{data.summary.verificationRate}% verified</small></article><article><span>Verified tokens</span><strong>{data.summary.verifiedTokens}</strong><small>{data.summary.rejectionRate}% rejected</small></article></section><section className="analytics-grid"><article className="panel funnel-panel"><p className="eyebrow">PARTICIPATION FUNNEL</p><h2>From registration to verification</h2><div className="funnel">{funnel.map((step) => <div key={step.label}><span>{step.label}</span><div><i style={{ width: `${(step.value / maxFunnel) * 100}%` }} /></div><strong>{step.value}</strong></div>)}</div></article><Trend title="Inventory activity" data={data.trends.inventoryEvents} color="#5d8cff" /><Trend title="New community memberships" data={data.trends.newMemberships} color="#2ed18b" /></section><p className="generated">Generated {new Date(data.generatedAt).toLocaleString()}</p></>}</main>;
}
